### ISSUE TITLE
1 low severity vulnerability

### ISSUE THREAD

**Issue by philwareham** [outaTiME/grunt-replace#100]
Please see https://github.com/outaTiME/applause/issues/14

**Comment by ntwb** [comment]
@vladikoff @outaTiME I'm happy to investigate further if you could help to help make a new release please?

----
│            Some vulnerabilities require your attention to resolve            
│ Low           │ Prototype Pollution                                          
│ Package       │ lodash                                                       
│ Patched in    │ >=4.17.5                                                    
│ Dependency of │ grunt-replace [dev]                                          
│ Path          │ grunt-replace > applause > lodash                            
│ More info     │ https://nodesecurity.io/advisories/577

**Comment by gbochenek** [comment]
In case anyone is still looking for this, I published a new fork to bump dependencies:

https://github.com/gbochenek/grunt-replace-regex

**Comment by noahcooper** [comment]
@outaTiME now that you've updated applause to fix this vulnerability, any chance you could update this plugin?

**Comment by outaTiME** [comment]
Sure @noahcooper im working on it 💪

**Comment by outaTiME** [comment]
Done 🚀
