### ISSUE TITLE
Change filename with timestamp?

### ISSUE THREAD

**Issue by andyscott12** [outaTiME/grunt-replace#29]
I am trying to use grunt-replace to actually update a filename with the timestamp so it appears like

```
myfile.34242342343.js
```

Can I do this with grunt-replace ? Are you able to help.

**Comment by sahanDissanayake** [comment]
@andyscott12  Im using SailsJS and in the core we use grunt
https://stackoverflow.com/questions/29726899/sailsjs-how-to-add-a-build-timestamp-at-the-end-of-the-minified-files

Could you help me figure out a way to add a time stamp at the end of the file please ?

Are you familiar with SailsJS
