### ISSUE TITLE
It's too easy to fail at string replacement task due to prefix

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [outaTiME/grunt-replace#43]
It's easy when going over the documentation too quickly to assume that a string replacement is just that, a simple string replacement, however this is not the case at all, the string replacement is specifically looking for the string with a prefix string of '@@' out of the box.

I know I made this assumption and others have as well after reading through some issues.

To be fair, it does seem confusing that a simple string replacement isn't just that: a simple string replacement.  It *is* documented that it works the way it does, but it's not the automatically assumed behaviour most people would expect in my opinion so this leads to a lot of people probably wondering why it's not replacing their strings.

I see two potential solutions:

1) Change the behaviour to just do a simple string replacement and do away with the prefix option completely.  As far as I can tell it's redundant and unnecessary and just leads to this confusion to new users, not to mention it increases the code footprint of the module and complexity to use it.  People who use a special prefix could just prepend it to their search string, no need for a separate option for it unless I'm missing a use-case that requires it.

2) If the module can't be changed at this point then it could output to console that the string was not found in such a manner as to convey to the user that they might have forgotten to prefix their text in their source file with the special prefix characters.  Something like:

'String "@@FOO" not found, nothing to process.  Did you forget to prefix your search string?  Grunt-replace expects to find your search string "FOO" with a prefix of "@@" like this: "@@FOO".'

Where FOO is substituted with their search string from the config and @@ is substituted with the prefix from config if different.

**Comment by amclin** [comment]
Ok, this would have saved me an hour just now - that's a pretty important distinction. At the least the examples in the readme should be updated

**Comment by steve-king** [comment]
+1

Skimmed the docs as I just wanted a quick string replace. More haste, less speed I suppose, but I think the default behaviour should definitely be changed.

**Comment by outaTiME** [comment]
In the meantime i will releasing a new version, what do you got in mind guys ... in cannot change de default behaviour a lot of people running this module in production environment ... 

I thing the best effort can i do is show warning when no replacement found, what do you thing ??

If one of use got something else in mind can make a PR with your idea ...

**Comment by WhatFreshHellIsThis** [comment]
At least include a warning message as I suggested in my first post **LAST SUMMER!!**

**Comment by outaTiME** [comment]
Hahaha, i got it ... Soooooon ;)

**Comment by outaTiME** [comment]
baaack again guys !!! 

we have a lot of work but ... this week (probably) i will be releasing a new version with some fixes ...

here little screenshot with the warning message, what do you think ??

![screen_shot_2015-04-30_at_18_57_52](https://cloud.githubusercontent.com/assets/140472/7423503/452a1ea8-ef6c-11e4-856d-9bb5184112fd.png)

its only shows when simple variable lookup and the `usePrefix` flag is enabled and obviously when any of the defined patterns are not matched take a look
