### ISSUE TITLE
If inner key-value pair doesn't exist, replace as blank (empty)

### ISSUE THREAD

**Issue by doshprompt** [outaTiME/grunt-replace#55]
currently, it replaces the outer as object and leaves the rest of the string intact (after the dot notation) like so:

FOO - {"title":"FOO"}.description

**Comment by outaTiME** [comment]
Hi pal, its impossible to detect the full "token", `applause` replaces the first occurrence on the matching tree ...

the bigger match should be replaced at first if we found "@@inner.hai" in the matching tree it will be resolved before "@@inner" ... im unable to resolve this kind of replacement =(

if you got some idea how to deal with that, PR will be welcome ...

**Comment by outaTiME** [comment]
no updates, closing for now ...
