### ISSUE TITLE
feature request: { options: { stdout: false, stderr: false } }

### ISSUE THREAD

**Issue by AMA3** [outaTiME/grunt-replace#62]
It would be Awesome™ if grunt-replace provided the ability to suppress messages a la grunt-shell's { options: { stdout: false, stderr: false } }

**Comment by outaTiME** [comment]
Hi pal, soooon it will released ...

**Comment by AMA3** [comment]
Thank you!

**Comment by outaTiME** [comment]
Not yet released but in this days ...
