### ISSUE TITLE
"Failed to parse json" error when installing via npm

### ISSUE THREAD

**Issue by jgillman** [outaTiME/grunt-replace#63]
When I install with npm (`npm install grunt-replace --save-dev`) I get the following error

```sh
npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "grunt-replace" "--save-dev"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.10
npm ERR! file /home/vagrant/.npm/combined-stream/0.0.7/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /home/vagrant/.npm/combined-stream/0.0.7/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /myProject/npm-debug.log
```

I can include `/myProject/npm-debug.log` if needed, but it's 20700 lines long...

Out of curiosity I also tried installing the previous version (0.7.9) but got the same error.

**Comment by outaTiME** [comment]
Pal, how are you ??? 

Any update with this ?? Im unable to reproduce this issue ... 

thks

**Comment by jgillman** [comment]
@outaTiME To be honest I haven't touch this project since I posted this issue. If I dig into it more I'll see if I can reproduce the issue again. Until then I'll close the issue.

**Comment by gef756** [comment]
I ran into the same issue...it looked like the download was corrupted. I was able to fix it by running `npm cache clean` or deleting the directory with `rm -r ~/.npm/combined-stream/`. Hope that works for you too!

**Comment by watashiSHUN** [comment]
@gef756, thanks so much I had a similar issue...with grunt-contrib-uglify,
you saved my day
