### ISSUE TITLE
coffee script support?

### ISSUE THREAD

**Issue by mmahalwy** [outaTiME/grunt-replace#64]

**Comment by outaTiME** [comment]
Hi pal, 

what do you have in mind ??? how do you imagine this ???

thks !

**Comment by mmahalwy** [comment]
config.js should output as config.coffee so if my scripts folder is all coffeescript and I am using the grunt coffeescript compiler, it should compile the config.coffee with it too. Rather, I had to do this hack to get it working:
```
dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/scripts',
          src: '{,*/}*.{coffee,js}',   <------------------------
          dest: '.tmp/scripts',
          ext: ".js",
          extDot: "last"
        }]
      },
```

**Comment by mmahalwy** [comment]
Great plugin BTW - love it!!

**Comment by outaTiME** [comment]
Please, do you got a full example escenario ??? 

I dont understand what are you trying to do .... 

thks pal !

**Comment by mmahalwy** [comment]
Hey Ariel,

Sorry I will get back to this later today!

On Sun, Mar 1, 2015 at 8:15 PM, Ariel Falduto <notifications@github.com>
wrote:

> Please, do you got a full example escenario ???
>
> I dont understand what are you trying to do ....
>
> thks pal !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/outaTiME/grunt-replace/issues/64#issuecomment-76656523>
> .
>



-- 
*Mohamed El Mahallawy*



*@mmahalwy4167101981*

**Comment by outaTiME** [comment]
Hi pal, anything about that ?? in will releasing a new applause version soon ... 

thks !

**Comment by outaTiME** [comment]
No feedback, closing from now ...
