### ISSUE TITLE
Add option to output unsatisfied replacements

### ISSUE THREAD

**Issue by kevireilly** [outaTiME/grunt-replace#65]
It might be interesting to find out when a replacement is requested but never actually replaces anything. In a scenario where a recent commit, pull request, or otherwise stops satisfying an expected pattern, this could raise a warning to help you identify the change and potential need for an adjusted replacement pattern.

**Comment by outaTiME** [comment]
Hi pal, 

This issue is related with #66 ??

**Comment by kevireilly** [comment]
Correct, this is handled by outaTiME/grunt-replace#66 and outaTiME/applause#2
