### ISSUE TITLE
Can I use the found pattern in my replace function?

### ISSUE THREAD

**Issue by geri777** [outaTiME/grunt-replace#70]
I have a config.js file containing a version number. I would like to increment this number with each build.

I would like to do something like this:

```js
match: /'version' : '([0-9]+\.[0-9]+\.[0-9]+)'/g,
    replacement: function () {
        var version = $2++;
        return '\'version\' : \'' + version + '\''; 
    }
```

Is there a possibility to get the match result into the function?

Thanks!

**Comment by outaTiME** [comment]
hi pal ... 

why no use an version number tag an update each time you want ??? something like:

https://github.com/outaTiME/grunt-replace#multiple-matching

i think this way is more clear ...

**Comment by outaTiME** [comment]
Hi pal, anything about that ?? in will releasing a new applause version soon ... 

thks !

**Comment by outaTiME** [comment]
No feedback, closing from now ...
