### ISSUE TITLE
Reg Ex disappears?

### ISSUE THREAD

**Issue by webdevotion** [outaTiME/grunt-replace#71]
When running my command I would expect `grunt-replace` to find / replace a given reg exp:
```ruby
/img:(.*\.\b\w+)/
```
It works fine in most cases, but does not seem to catch filenames with `@2x`.  All though my reg ex pattern seems to be working fine on [Rubular](Rubular.com ), `grunt-replace` does not seem to appreciate the `@` signs in the file name.

So I started to debug:  as you can see below ( from the output ) the `match` value ( = my reg ex ) seems to disappear when  running `grunt replace` with the `--verbose` flag in order to see what is happening.

Command:
```
grunt replace:img_src --verbose
```

Task:
```js
    replace: {
      img_src: {
        options: {
          patterns: [
            {
              match: /img:(.*\.\b\w+)/g,
              replacement: "<%= images %>/$1"
            }
          ]
        },
        files: [{ expand: true, src:["<%= dist %>/**/index.html"], dest:'./'}]
      }
    }
```

Important part from the output ( see empty `match` key value ):
```
Options: .... patterns=[{"match":{}, ...
```

All the output:
```
...
Running "replace:img_src" (replace) task
Verifying property replace.img_src exists in config...OK
Files: dist/index.html -> dist/index.html
Options: encoding="utf8", mode=false, processContentExclude=[], patterns=[{"match":{},"replacement":"/assets/images/$1"}], excludeBuiltins=false, force, verbose
Reading dist/index.html...OK
Processing source...Replace dist/index.html → dist/index.html
OK
Writing dist/index.html...OK

Done, without errors.
```

**Comment by outaTiME** [comment]
Hi pal, 

mmm strange escenario, i try to replicate ... but i dont know if verbose shows complex object in std like regexp (if you use a basic regexp it doesnt show too i think but it does not mean it is no working) ...

Like you said some replacements does fine not ?? 

can you share a your template file (the index.html) and and as it should be ...

**Comment by outaTiME** [comment]
I repeat i think the regexp objects not shown in verbose ... unless the match attribute was an string

**Comment by outaTiME** [comment]
Hi pal, anything about that ?? in will releasing a new applause version soon ... 

thks !

**Comment by outaTiME** [comment]
No feedback, closing from now ...
