### ISSUE TITLE
Fails silently if no permissions to overwrite file

### ISSUE THREAD

**Issue by facultymatt** [outaTiME/grunt-replace#73]
In cases where the user does not have permission to overwrite files, the replace process fails silently. 

Running with `sudo` fixes this. 

But there should be an error to the user, because if they are not aware what is happening they will not know this fix.

**Comment by outaTiME** [comment]
Hi pal, ok ... let me see what can i do for this ...

thks for the feedback :+1:

**Comment by outaTiME** [comment]
mmmm, could you send me a little snippet about that ???

the grunt file write must be thrown an error, take a look:

https://github.com/gruntjs/grunt/blob/master/lib/grunt/file.js#L301

im using `grunt.file.copy`  and this method call to the above method and if something fails throws an error.

**Comment by outaTiME** [comment]
No feedback, closing from now ...
