### ISSUE TITLE
Escape special characters

### ISSUE THREAD

**Issue by wassimsalib** [outaTiME/grunt-replace#76]
Hi, I have a grunt task that replaces my current config based on the selected environment (i.e. development or production), but the problem is that one of my environment settings is an api key that contains "$$" in the middle of the string, when grunt-replace task runs, it gets replaced like this "$" so there is another dollar sign missing, and I think that is because it assumes it is a regular expression and I couldn't escape it, so is that a bug or how I make it as a literal string. This is how my code looks like:

Gruntfile.js
```
replace: {
      development: {
        options: {
          patterns: [{
            json: grunt.file.readJSON('./config/environments/development.json')
          }]
        },
        files: [{
          expand: true,
          flatten: true,
          src: ['./config/config.js'],
          dest: '<%= yeoman.app %>/scripts/modules/app/services'
        }]
      },
      production: {
        options: {
          patterns: [{
            json: grunt.file.readJSON('./config/environments/production.json')
          }]
        },
        files: [{
          expand: true,
          flatten: true,
          src: ['./config/config.js'],
          dest: '<%= yeoman.app %>/scripts/modules/app/services'
        }]
      }
    }
  });
```
development.js
```
{
  "API_BASE_PATH": "https://localhost",
  "API_KEY":"12213lkhgjhvj$$bvhmvff@sdfertvc"
}
```
config.js
```
'use strict';

angular.module('services.config', [])
  .constant('configuration', {
    API_BASE_PATH: '@@API_BASE_PATH',
    API_KEY: '@@API_KEY'
  });
```

**Comment by outaTiME** [comment]
Hi pal, i will check ... 

thks !!!

**Comment by outaTiME** [comment]
Sorry for delay, in working on this issue right now ... stay in touch ... 

thks !

**Comment by outaTiME** [comment]
Im releasing a fix soon for this scenario.

For JSON, YAML and CSON now we treat replacements as literal to prevent this issues, sounds great ??

**Comment by wassimsalib** [comment]
That will be great :+1: , so when it won't be considered as regex not literal? what about when you are defining the config you make different syntax for literals than regex, so for example
    API_KEY: '@@API_KEY' (will consider it as regex)
    API_KEY: '@@@API_KEY' (will force literal)

Just saying...

**Comment by outaTiME** [comment]
All attributes readed from JSON, YAML and CSON will be treat as "literal" not be affected for javascript replace special characters ($$, $&, $`, $', $n or $nn):

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

the rest remains the same, when i release the new version try your original code and it might works

**Comment by wassimsalib** [comment]
ok good, please let me know once you update the npm module

**Comment by outaTiME** [comment]
Version grunt-replace@0.9.3 released, enjoy your fix =)

**Comment by wassimsalib** [comment]
Working like charm :+1:  Thanks a lot :wink:
