### ISSUE TITLE
Get the path of the file which is currently being processed

### ISSUE THREAD

**Issue by vdininski** [outaTiME/grunt-replace#78]
I am trying to find a way to get the path of the file which is currently being processed and replace a placeholder with the path name. Not sure if this is possible right now...

**Comment by outaTiME** [comment]
Hi pal, do you checkout this:

https://github.com/outaTiME/grunt-replace#built-in-replacements

Here an example:

https://github.com/outaTiME/grunt-replace#how-to-insert-filename-in-target

**Comment by outaTiME** [comment]
No updates, closing for now ...
