### ISSUE TITLE
Update Documentation to include examples with '@@' sooner

### ISSUE THREAD

**Issue by osidenate** [outaTiME/grunt-replace#79]
After quickly setting this up, I was confused why this plugin wasn't matching my text. After looking at the documentation closer, I found out it was because I was not putting '@@' in front of the strings that need to be replaced. It took me awhile to figure this out and there is not API documentation for the "patterns" or "match" options. Please include examples with '@@' earlier on in the docs or have an API references for "match". Thanks for making a solid plugin.

**Comment by outaTiME** [comment]
Hi pal, 

Sorry in the last release readme file broken, i fix it soon ... thanks !!!

**Comment by outaTiME** [comment]
Fixed, check out the new docs .. my fault =(
