### ISSUE TITLE
ANSI File

### ISSUE THREAD

**Issue by emalherbi** [outaTiME/grunt-replace#81]
Hi.

I have a file "install.iss" in ANSI codification, this file is generated automatic. So if a replace the file "install.iss" using "grunt-replace" the new file codification is UTF8, but some erros show in file, see example: 

```
Configuração do SQL Server
``` 

```
Configuraï¿½ï¿½o do SQL Server
```

Is possible to use only ANSI format in this case? 

Tks.

**Comment by outaTiME** [comment]
Hi, pal ... something wired probably it comes from grunt ... i will check soon ...

thks !

**Comment by outaTiME** [comment]
Hi pal, now you can try to use your own encoding using the encoding flag:

https://github.com/outaTiME/grunt-replace#encoding

It uses uft-8 by default (http://gruntjs.com/api/grunt.file#grunt.file.defaultencoding), you could try something like:

```
{
  patterns: [
    {
      match: 'foo',
      replacement: 'bar'  // replaces "@@foo" to "bar"
    }
  ], 
  encoding: 'ascii'
}
```

I wait for your feedback ... thks !

**Comment by emalherbi** [comment]
Hey man, 

Not work's. See :( 

```
Input:
Configuração do SQL Server

Output:
Configuragco do SQL Server
```

But it is not necessary to change anything, I made changes in my original file and removed the accentuation.

**Comment by outaTiME** [comment]
oups bad news, you could try another encoding ... 
we delegate encoding logic to grunt core ... it might be work

**Comment by outaTiME** [comment]
you could try:

```js
{
  patterns: [
    {
      match: 'foo',
      replacement: 'bar'  // replaces "@@foo" to "bar"
    }
  ], 
  encoding: 'iso-8859-1'
}
```

**Comment by emalherbi** [comment]
Hey man,

It's work.

Tnks

**Comment by outaTiME** [comment]
:+1:
