### ISSUE TITLE
Regex file replacement at group.

### ISSUE THREAD

**Issue by mchambaud** [outaTiME/grunt-replace#84]
Hi,

I'm trying to replace a certain script with another one but I can't figure out out to insert the file at $1.

Here's my code, works but script tag goes away.

    patterns: [{
        match: /<script id="config" \b[^>]*>([\s\S]*?)<\/script>/,
        replacement: '<%= grunt.file.read(directory.build + "/"+environment+"/config.json") %>'
    }]

I already have a solution but I'm not happy with it, I though maybe there was a more elegant way to achieve this.

    patterns: [{
        match: /(<script id="config" \b[^>]*>)([\s\S]*?)(<\/script>)/,
        replacement: '$1<%= grunt.file.read(directory.build + "/"+environment+"/config.json") %>$3'
    }]

**Comment by outaTiME** [comment]
Hi pal, 
you could try:

```js
patterns: [{
    match: /<script id="config" \b[^>]*>([\s\S]*?)<\/script>/,
    replacement: function(match, p1) {
        return return grunt.file.read(directory.build + "/" + p1 + "/config.json");
    }
}]  
```

**Comment by mchambaud** [comment]
HI @outaTiME,

Actually, I don't care about the content of the script, I want to replace it with the content of the config.json.

**Comment by mchambaud** [comment]
@outaTiME 

    replacement: function(match, p1) {
       return grunt.file.read(directory.build + "/" + p1 + "/config.json");
    }

this will not work. When ever I call grunt or variables from replacement function it fails with "Warning: Error while processing "..." file

**Comment by outaTiME** [comment]
i again pal, i don't know how environment variable was define but it your grunt is defined like that it might be work:

```js
{
    match: 'config',
    replacement: function() {
        return grunt.config.get('environment');
    }
},
```

**Comment by outaTiME** [comment]
it works ?

**Comment by mchambaud** [comment]
Unfortunately, no.

**Comment by outaTiME** [comment]
Mmm, probably something wrong in your gruntfile, do you want to share with us your fully file ?

**Comment by mchambaud** [comment]
My grunt file is massive.. Do you have a working example with? Otherwise I will start a fresh project to see if it works.

**Comment by outaTiME** [comment]
Here basic example:

Gruntfile.js

```js
module.exports = function (grunt) {

  // define the configuration for all the tasks
  grunt.initConfig({

    // environment
    environment: 'dev',

    // replace task
    replace: {
      config: {
        options: {
          patterns: [
            {
              match: 'config',
              replacement: function() {
                return grunt.config.get('environment');
              }
            }
          ]
        },
        files: [
          {expand: true, flatten: true, src: ['fixtures/environment.txt'], dest: 'tmp/'}
        ]
      }
    }

  });

  // load tasks
  grunt.loadNpmTasks('grunt-replace');

  // default task
  grunt.registerTask('default', [
    'replace'
  ]);

};
```

fixtures/environment.txt:

```
@@config
```

tmp/environment.txt:

```
dev
```

**Comment by outaTiME** [comment]
Here the complete working example:

https://cloudup.com/cnjwEtEKSlF

**Comment by outaTiME** [comment]
Updates ??

**Comment by mchambaud** [comment]
Sorry haven't had a chance to try until just now, it works =)

Thanks!
