### ISSUE TITLE
change destination file name

### ISSUE THREAD

**Issue by donalmurtagh** [outaTiME/grunt-replace#86]
I would like to replace the variables in `/template/foo.js.tpl` and store the result in `/config/foo.js`. I tried the following configuration

        files: [
          {
            expand: true,
            flatten: true,
            src: ['/config/template/config.js.tpl'],
            dest: '/config/config.js'
          }
        ]

But that results in the output file `/config/config.js/config.js`. Is it possible to specify an output filename that is different from the template file name?

**Comment by outaTiME** [comment]
Hi pal, 

you could try the following:

```js
files: [
  {
    expand: true,
    cwd: 'config/',
    src: ['template/config.js.tpl'],
    dest: 'config/',
    rename: function(dest, src) {
      return dest + src.replace(/\.tpl$/, "");
    }
  }
]
```

**Comment by donalmurtagh** [comment]
@outaTiME thanks a lot, I'll give it a shot. Is `rename` covered in the docs? If so, I must have overlooked it

**Comment by outaTiME** [comment]
The ´readme´ atriburte is part from grunt core, take a look:

http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically
