### ISSUE TITLE
Recursive call of replacement function?

### ISSUE THREAD

**Issue by stephanfriedrich** [outaTiME/grunt-replace#89]
@outaTiME, Hi i tried to improve the replace functionality, which we use in [generator-kickstart](https://github.com/OpenSourceWorkflow/generator-kickstart).

i wrote a iterative replacement function within your Replace Task, but a recursive call could also work. _Unfortunately i dont know how to call Replace Task recursiv, can you help me?_

please, take look at my [pull-request](https://github.com/OpenSourceWorkflow/generator-kickstart/pull/150#issuecomment-188222875)

greetings

**Comment by outaTiME** [comment]
Hi pal, sorry for delay ... im back in town again ... 

any update of this feature ??

**Comment by stephanfriedrich** [comment]
nope, unfortunately not.
hope you can help me, or you have some ideas/ links to read about it.

**Comment by stephanfriedrich** [comment]
@outaTiME here is my replace function, can you take a look at it, please ?:

```
 replace: {
      modules: {
        options: {
          excludeBuiltins: true,
          patterns: [
            {
              match: /{(app|deferred):{([\w|\-]{0,})}}/g,
              replacement: function (match, type, file) {

                / *** use regular file

                / *** add app folder to deferred component
                type = type === 'deferred' ? 'app/_' + type : type;

                / *** get file for replacement
                output =  grunt.file.read('components/' + type + '/' + file + '/' + file + '.html');

                / *** check if output include some 'app placeholder'
                match = output.match( /{(app):{([\w|\-]{0,})}}/g );
                if( match !== null ) {

                  // *** replace each placeholder with its accociated file content
                  match.forEach(function(elem){
                    var
                    inner_match = elem.replace( /[{}]/g,'').split(':'),
                    inner_type = inner_match[0],
                    inner_file = inner_match[1],
                    inner_regex = new RegExp("{("+inner_type+"):{"+inner_file+"}}", "g"),

                    inner_output =  grunt.file.read('components/' + inner_type + '/' + inner_file + '/' + inner_file + '.html');

                    / *** write file content into main output
                    output = output.replace( inner_regex , inner_output );
                  });

                }

                return output;
              }
            }
          ]
        },
      }
   }
```

**Comment by outaTiME** [comment]
Hi bro, 

Tomorrow i will check, ok ??

**Comment by stephanfriedrich** [comment]
Hi, thx for your fast respond.
And you are right, i update the code snipped. 

You can find [here](https://github.com/stephanfriedrich/generator-kickstart/blob/2dfbf789272558082648f98fb729e753a8698caa/app/templates/_gruntfile.js) the complete grunt file.

**Comment by stephanfriedrich** [comment]
Hi @outaTiME, anny ideas ? .. greetings

**Comment by stephanfriedrich** [comment]
ping :-)

**Comment by outaTiME** [comment]
stale, you could try the new version to see if this problem is solved, closing for now
