### ISSUE TITLE
Document replace function arguments

### ISSUE THREAD

**Issue by julmot** [outaTiME/grunt-replace#96]
There aren't any information about arguments passed to the replacement function available in the documentation.

**Comment by outaTiME** [comment]
hi @julmot, the only way to "explicitly" call the replace using a function is documented her:

https://github.com/outaTiME/grunt-replace#patternsreplacement-or-patternsreplace

**Comment by julmot** [comment]
The function itself is documented, but not its arguments/parmeters.  
For example the information that matching groups are passed as parameter to this function would be helpful.

**Comment by outaTiME** [comment]
it took the same arguments as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace, its an proxy.

**Comment by julmot** [comment]
Again, then this should be documented. That's all.

**Comment by outaTiME** [comment]
Understood, a PR will be welcome 👍

**Comment by outaTiME** [comment]
It was added to the `readme.MD` long time ago, 
thanks for your support @julmot, closing for now.
