### ISSUE TITLE
Dependency issue on install

### ISSUE THREAD

**Issue by RitualOfFlame** [outaTiME/grunt-replace#97]
Hello,

looks like the 1.0.1 version (latest atm) is looking for coffee-script@^1.10, which is generating problems when a BeforeBuild 'npm install' instruction is executed. 
This is probably because coffee-script NPM package has been lately renamed to coffeescript. Can you give me a feedback regarding this? Appreciate, thanks for your time

**Comment by enmanuelsaravia** [comment]
yes please, i too want a regarding this please send me the repair command, i get the same problem :'(
how to fix please

**Comment by outaTiME** [comment]
After a long time, today I took a moment to update the different modules, I hope it helps. 🚀
